/* tslint:disable */
/* eslint-disable */
/**
 * ScriptAB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Candidate
 */
export interface Candidate {
    /**
     * 
     * @type {number}
     * @memberof Candidate
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof Candidate
     */
    userid?: any;
    /**
     * 
     * @type {Array&lt;Skill&gt;}
     * @memberof Candidate
     */
    skills?: any;
}
