/* tslint:disable */
/* eslint-disable */
/**
 * ScriptAB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * 
     * @type {number}
     * @memberof Company
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof Company
     */
    userid?: any;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    size?: any;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    image?: any;
    /**
     * 
     * @type {Array&lt;Job&gt;}
     * @memberof Company
     */
    jobs?: any;
}
