/* tslint:disable */
/* eslint-disable */
/**
 * ScriptAB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    phone?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    image?: any;
    /**
     * User Status
     * @type {number}
     * @memberof User
     */
    userStatus?: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    candidateId?: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    companyId?: any;
}
