/* tslint:disable */
/* eslint-disable */
/**
 * ScriptAB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from "axios";
import { Configuration } from "../../../api/configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../../../api/base";
import { Candidate } from "../models";
/**
 * CandidateApi - axios parameter creator
 * @export
 */
export const CandidateApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * This can only be done by the logged in user.
     * @summary Delete user
     * @param {number} id id of candidate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCandidate: async (
      id: number,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          "id",
          "Required parameter id was null or undefined when calling deleteCandidate."
        );
      }
      const localVarPath = `/candidate/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary get candidate by their id
     * @param {number} id id of candidate.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCandidateById: async (
      id: number,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          "id",
          "Required parameter id was null or undefined when calling getCandidateById."
        );
      }
      const localVarPath = `/candidate/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * This can only be done by the logged in user.
     * @summary Updated candidate
     * @param {Candidate} body Updated user object
     * @param {number} id id of candidate.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCandidate: async (
      body: Candidate,
      id: number,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling updateCandidate."
        );
      }
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          "id",
          "Required parameter id was null or undefined when calling updateCandidate."
        );
      }
      const localVarPath = `/candidate/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "*/*";

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      const needsSerialization =
        typeof body !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || "";

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CandidateApi - functional programming interface
 * @export
 */
export const CandidateApiFp = function (configuration?: Configuration) {
  return {
    /**
     * This can only be done by the logged in user.
     * @summary Delete user
     * @param {number} id id of candidate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteCandidate(
      id: number,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await CandidateApiAxiosParamCreator(
        configuration
      ).deleteCandidate(id, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     *
     * @summary get candidate by their id
     * @param {number} id id of candidate.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getCandidateById(
      id: number,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Candidate>
    > {
      const localVarAxiosArgs = await CandidateApiAxiosParamCreator(
        configuration
      ).getCandidateById(id, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * This can only be done by the logged in user.
     * @summary Updated candidate
     * @param {Candidate} body Updated user object
     * @param {number} id id of candidate.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateCandidate(
      body: Candidate,
      id: number,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await CandidateApiAxiosParamCreator(
        configuration
      ).updateCandidate(body, id, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * CandidateApi - factory interface
 * @export
 */
export const CandidateApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     * This can only be done by the logged in user.
     * @summary Delete user
     * @param {number} id id of candidate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCandidate(id: number, options?: any): AxiosPromise<void> {
      return CandidateApiFp(configuration)
        .deleteCandidate(id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary get candidate by their id
     * @param {number} id id of candidate.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCandidateById(id: number, options?: any): AxiosPromise<Candidate> {
      return CandidateApiFp(configuration)
        .getCandidateById(id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * This can only be done by the logged in user.
     * @summary Updated candidate
     * @param {Candidate} body Updated user object
     * @param {number} id id of candidate.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCandidate(
      body: Candidate,
      id: number,
      options?: any
    ): AxiosPromise<void> {
      return CandidateApiFp(configuration)
        .updateCandidate(body, id, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * CandidateApi - object-oriented interface
 * @export
 * @class CandidateApi
 * @extends {BaseAPI}
 */
export class CandidateApi extends BaseAPI {
  /**
   * This can only be done by the logged in user.
   * @summary Delete user
   * @param {number} id id of candidate
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CandidateApi
   */
  public deleteCandidate(id: number, options?: any) {
    return CandidateApiFp(this.configuration)
      .deleteCandidate(id, options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   *
   * @summary get candidate by their id
   * @param {number} id id of candidate.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CandidateApi
   */
  public getCandidateById(id: number, options?: any) {
    return CandidateApiFp(this.configuration)
      .getCandidateById(id, options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   * This can only be done by the logged in user.
   * @summary Updated candidate
   * @param {Candidate} body Updated user object
   * @param {number} id id of candidate.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CandidateApi
   */
  public updateCandidate(body: Candidate, id: number, options?: any) {
    return CandidateApiFp(this.configuration)
      .updateCandidate(body, id, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
