/* tslint:disable */
/* eslint-disable */
/**
 * ScriptAB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Application
 */
export interface Application {
    /**
     * 
     * @type {number}
     * @memberof Application
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof Application
     */
    jobid?: any;
    /**
     * 
     * @type {number}
     * @memberof Application
     */
    candidateid?: any;
    /**
     * 
     * @type {number}
     * @memberof Application
     */
    companyid?: any;
}
