/* tslint:disable */
/* eslint-disable */
/**
 * ScriptAB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    companyId?: any;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    workplaceType?: JobWorkplaceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    employmentType?: any;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    salary?: any;
    /**
     * 
     * @type {Array&lt;Skill&gt;}
     * @memberof Job
     */
    skills?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum JobWorkplaceTypeEnum {
    Remote = 'Remote',
    Hybird = 'Hybird',
    OnSite = 'On-site'
}

