export const JobData = [
  {
    id: 1,
    title: "AI Developer",
    image: "/alta.png",
    company: "Atla.ML",
    location: "Edmonton",
    description: "AI Developer position open at Atla.ML",
    date: "2020-11-27",
    skills: [
      "Compter Science",
      "Research and Development",
      "Test Planning and Field Operations",
      "Process and Procedure Development",
    ],
  },
  {
    id: 2,
    title: "Backend Developer",
    image: "/neo.png",
    company: "Neo Financial",
    location: "Calgary",
    description: "Junior Backend Developer",
    date: "2020-11-25",
    skills: [
      "Computer Systems Analysis",
      "Data Collection and Analysis",
      "Computer Science",
    ],
  },
  {
    id: 3,
    title: "Hardware Engineer",
    image: "/amazon.png",
    company: "Amazon",
    location: "Calgary",
    description: "Junior Fullstack Developer",
    date: "2021-11-23",
    skills: [
      "Computer-based Transducers",
      "Test Planning and Field Operations",
      "Management Process",
      "System Characterization and Test",
    ],
  },
  {
    id: 4,
    title: "Staff Accountant",
    image: "/deloitte.png",
    company: "Deloitte",
    location: "Edmonton",
    description: "Accountant",
    date: "2021-11-21",
    skills: [
      "Auditing",
      "Accounting",
      "Finance",
      "Data Collection and Analysis",
    ],
  },
  {
    id: 5,
    title: "Auditor",
    image: "/calgary.png",
    company: "City of Calgary",
    location: "Calgary",
    description: "",
    date: "2021-11-11",
    skills: [
      "Financial",
      "Financial Reporting",
      "Data Collection and Analysis",
    ],
  },
];
